import type { Metadata } from "next";
import { Geist, Geist_Mono, Rock_Salt } from "next/font/google"
import "./globals.css";
import Header from "../components/header"
import Footer from "../components/footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rockSalt = Rock_Salt({
  weight: '400',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=".bg-vertical-reverse bg-fixed">
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
